name: CI and Deploy to Render

on:
  push:
    branches:
      - '**'            # run CI on every branch
  pull_request:         # also run CI on PRs

jobs:
  build:
    name: Frontend Build & Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./courier-app-web

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Build
        run: npm run build

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # deploy only on main branch

    steps:
      - name: Trigger Deploy on Render
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/deploy/srv-xxxxxxxxxxxx?key=${{ secrets.RENDER_DEPLOY_KEY }}

